### ISSUE TITLE
Merger of slide 6 and 7

### ISSUE THREAD

**Issue by TheRealJensJK** [SivertGullbergHansen/IDG_gc_1007_gc_12_GuardiansOfCSS#52]
When merging slide 6 and 7 I added a "hot fix" to App.js so slide 8 runs after slide 6, but the scroll manager still counts the skipped slide, so the slide number in the bottom gets out of sync (slide 8 runs twice).

**Comment by TheRealJensJK** [comment]
so the question is; is it easier to push all subsequent slides 1 place forward (-1 to the slide number) or to create a workaround?

**Comment by sivert-io** [comment]
I think changing the number of all slides is better than leaving one slide "empty" :) It doesn't matter which number they have, just that they run in sequence.

**Comment by sivert-io** [comment]
The scroll manager also only counts the times the user has scrolled in each direction based on when it is ready. So App.js doesn't affect the number on the loading bar. This could be changed of course so that app.js affects the scroll index, however then we'd probably have to start using a switch-case to handle which function to run (rather than the simple "string to function" that we're using now. 3 lines of code compared to the amount of slides + break and an index for each case).

Let's say we decide that each slide function changes the number of the scroll index. If all slides are in sequence then this becomes redundant? If all slides were out of sync or didn't have a number to represent it's position, then it would probably make more sense to say "If scroll index is 10 we play this function when scrolling up, and this function when scrolling down" and to then have the slide function affect the scroll index. I would still argue to replace the number values of the slidefunctions rather than creating a new system
